/*
 * Copyright (c) 2019 Embest Tech Co., Ltd
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/* Shield level DTS fixup file */

#define DT_MINODE_A0_NAME			DT_ELEMENT14_MINODE_CONNECTORS_CONNECTOR_0_LABEL
#define DT_MINODE_A1_NAME			DT_ELEMENT14_MINODE_CONNECTORS_CONNECTOR_1_LABEL
#define DT_MINODE_A2_NAME			DT_ELEMENT14_MINODE_CONNECTORS_CONNECTOR_2_LABEL

#define DT_MINODE_D12_NAME    DT_ELEMENT14_MINODE_CONNECTORS_CONNECTOR_12_LABEL
#define DT_MINODE_D13_NAME    DT_ELEMENT14_MINODE_CONNECTORS_CONNECTOR_13_LABEL
#define DT_MINODE_D14_NAME    DT_ELEMENT14_MINODE_CONNECTORS_CONNECTOR_14_LABEL
#define DT_MINODE_D15_NAME    DT_ELEMENT14_MINODE_CONNECTORS_CONNECTOR_15_LABEL

/* End of Shield Level DTS fixup file */